dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: VvQJTnwrIisaz6LVoBqPDLxYFPLSZmTTLKArUn2ZohRE60iu2dQGAI+TTa/YVUN45zqWHp7P5rFw5/F/lViFuuXi2MbmbZyagThD3eGyN5rVG21BG2cdlVLMeI8ZnQ3Jly14SWrFnroN1lUzUnTfjr0cjMNOyN1ZbH03Ldyp8PG/TWgPE8Su2S8hJz7EMX5XPOgG874bG+8PX60U2626L2j6H0kakAajuouXT2U1C1Iu3qHWopGS7lHWXER5F7M00ciFz8OzLPBSKJhG1OV1FpfftFZJRguiWRinT4mCaQx//++c//+5d51+FqR2I2oXJdFKwif/P9O6/7T2WnTdr1ZSaxAyVV573EBdo04W3SE8ei0cskqa3slRawjROlBKJ5VtcxkDM449/b6UzHVNssX44hWTY6vFC6D+rdw+IQmqH1fmKAw7kABxCMCKfQRK+IJlyzPnIBE3+rDxmsql+v8VItCRePAn+x/z0JlX8njblLaG77JfBnvxb4tEkCG48M8efmzV2xjIuPjhUULy4mWiXWgr28DnzBNbnKwyEPVOX5I3mDP/ynJMnz0K+sWgUMphQH9T/MSXbGWJscH8QPJIGLBRTkUahc6nvYqF15zWELCcZNHxWO21R4c46BqUCN9bVo1p3o2zpoJs94dl8p50nQhm6JLoA8Yo8/Wxx/U=
  - secure: HWePKbQHMcQfDnWW+qIAF05KpPXk8xMa6I2OpEWIA1jOxhglrjTnYCafMetp7oPTITQn3WxT+cFvuTK1K/MUoMWR2wuhyR/6NDSFhvPNu8Gh0UAJyBV8YYf2gV7bnw8ES2a15zromoo2++vqbQHnnxvz5RaHihGVKzDVb8ytVONMGNGm9aHlj+nv1XFeBDMRTdfSZXXU0O7TXMogHmfx1aySNqdEC/Hlas7PlFkyzPB2vdKlAFmwgOhrnfI8KMyR+XRuKARtUHLGHlNiaEdA+gIlGV5DAWHpRJIxt8iv/kETUl9sCFKEoFhXVEL6+BqSKcbiZpu4oSw+dm2NxxE1o8xnHec8zhVq3jOhwHlgrICVDpw5+EzR3/LdLmbqyZ+rSWfPgF6cyCeHvsOvDp5Xf5yHWo/lAjOgrhQdCAM2rFjfZRg7WjnsTRyvb3siFSm28MpNHKTTIuODDUx/J6gNzNpdGxsbi9kXuGHxw+k6WiXmOoPpPoWjkVCsJRSQAj2eq7L8Z1xA1AB/JAQh0t3rGsGS7VZXurjkMgbhU/8s9Mg/fxLDiWEzAvm1ax8aIbfnCZP7opTUg+r28mDnI6e7fGiKoXSdkyHZMs7Biyf63dtoPVxNWirxmlaQOfvTuXV+k12VvZoapxeg2aiP3YqjMGP+kgCTPWMBPnVZ3lLHCZ8=
  - secure: R9LK5ZpUNu2VbShSAgaTOm8SnGnC45HMIfXEFQy6Tz4xqCMqCeBr7E/ljiidsVkTTABbl2Xjd2D7NX6Qw/S3V6/aMG6AwVk/4yxMaX2fiFFR0weUCkKxgx8WxpreLM44DpCtpkmZyVQRZ2wvqMFQ3S1a9ZOYMYcNCNG++Lwlg6tFTa1vfblZ43DcM9mFTnGSj7Ng8qIDfyIU1y+uYEhvaBd2L6ZkmS1k33Ot7C1Tl7GQDDR/v+/+roJ/CkTchaeB0eFpArQI88Lt7/reZS7IIV5erXkW7p0ZO39E4BKCQLtPwtG8/gRIKuJG1uWFffQNiEfA1RcsG4Ejzf3OFm5DaXTB/vsQaKGSNJ/ytBIJ/oEZRcQWAlDLa8vnQ+KhjHWIHvsGi2TZE8NYm2+ViThRbTtlCpVGKTbEq3TVkOaCnyASjBr/ClGDYYcpOXGClFWT++jpVG7DENm3htzAssyHJczWyGAF+F0uoxE9sz+lExuBNDPAazAWd5SnakYyGpanHqdgTKfOxfXG2aeHOW4eobN08sh1+VtUIMcI4EBXac7F95w18d3ghmy3N42XzKA3M1kyydbZIR83KHyE+CVbuBRjWAgDKbhFL5ZjIKdUSh4n6ZIJMkt7q8g1cXSidQ9kP0BSaFWBy7TzRc87FJUFAKU6omtQ9IWefoTIt8whK7c=
  - secure: fJku+y+kwd0izIOK7k4oyCGGp7wmYLBwhi/tLLou5LiuxwWhigARBYAWTBQa5jCEtEP/MLSzkCE8b7IcMaYwKkqk3rL9Or9wjwaF8vNOfUgdluhoUzZpFZQ6dcIH1ugAuTT0OLki4GYxi4EjEkhCCzQvunT+thAc1mxPpiJ+n1yAD6QeWXw0AemSVfkxgoP+peJVGI72lIcc8xsnhfcUDhX3O82gkRAlIWmZE92D1Z73ro2/EvFWIR5+uIxo16qVN4V1rgRn8xCPgJ9KRM/qMIznXg2+0Zr4RMDIYLYD7k3D91M2n9mvLQ6v8w7lHLbSm0tP7QS18kdfsydbyHGHxjBqQxUf2zH10IWUO0RnABYQjXq2L4Q8j3xO4V+Hk3e5u12LHvfIcLAL2TpSuVsTalAlprOviGLTfAJGGB7xhbEB9o1r4ikIM+Zb4JYq9bJp60wY9Q/oOhV95gKcFWVe2rAluxc0qJE0YVFULJYnYLCOhtRg7zXaSW7BTAYLk8dEKRWQzKvSSs7Xmco3mLw0/WYK9WFLK/zHfpp8XSGSxIMZBXtZdDyms8I4V9qsxlvn44jk3HVLnI0LmGfQ7QlbAXULz+xw+QajovyDOKdf3UKENpnJO0GMpfvjYvkIXL6qeFisGdFKpKgnedY+nza2BzBp9nnUbfCOJsxUOO1prys=
install: true
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: WwzZgxGbhvXsPrCr/Fq6Udhb+4jrXRZar4ahbS5oCJF9ARWqZYl61fYrGoDzjjvTopcbT/XcYZDFtij4UvyodcJ0Q5HM6H64TZQZ4cPTRMbwfxtsXrFqbJDJJYqxWTlAD2qWiWmysyfcmDS9TS1no93ptoiaDcrZK0hAvy3+fsfF92HsVeG46uZLFhHvhCfL4QjP/gacdaGyJVokuv0pn83kPIkgaBa1plxBDMd0jOsqpOkuxDV/qDpBewdMT/lRvShiv6txqazK3lgzfObLKos4ItcieOm18bjjFigwF6pqzmAZ/12KvdPGW0iT40zHenlsnZSPnAn84HFFIwlV/ktuu6FRw1uGArEVG8jyJ/Imss8JtqlWrLCtlRnk42zYvLhI+Yf3ma8Der0JjZKN9JHHqVN3nXazjgdV4NmFp9sNhph2SHa+TCV2gSxAVqAeGqEsMTzMD28BzfBFLZ7ucD+th6P3c62NxMlfhArpXdYznp/KpcKzkVs1MDyEjZPFwvDOXOsIBK2xJAd+6xb7aS3hwvxJdFZwh5nCtWrIpj/x/CA+tPh8WkmRJ/UlQ9gmI7hPm3Yzs3be8A0qUjWFpA4m0QKqXWiWsSUxH43wsc8VdsLi05w5+F38ru4yu97XZRCza5ZQKE/iH5z7sX9J6qH9ESNbHVbQzGTvAxoE8ks=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
addons:
  apt:
    packages:
    - openssl
    - gnupg
before_install:
- openssl aes-256-cbc -K $encrypted_50608fee9b7e_key -iv $encrypted_50608fee9b7e_iv
  -in atomist_sec.gpg.enc -out atomist_sec.gpg -d
